### ISSUE TITLE
[FEATURE] Add change log

### ISSUE THREAD

**Issue by luipir** [fpsampayo/zoomrc#1]
Would be better to use metadata to log changes. e.g explain that last version add the feature to hilight the RC polygon.
Do it getting the example from other plugins.

**Comment by fpsampayo** [comment]
Hi Luigi! I just saw this issue. I add this on next realease.

**Comment by fpsampayo** [comment]
Luigi, maybe i don´t understand you. I think that you refer to this? https://github.com/fpsampayo/zoomrc/blob/qgis-3.0/metadata.txt#L27
