### ISSUE TITLE
Error in ZoomRC

### ISSUE THREAD

**Issue by EmilioAAbad** [fpsampayo/zoomrc#2]
Hi Francisco,

I can not use the complement because I get the following error, after entering a valid cadastral reference: Aviso. Error al obtener coordenadas.
I have tried to configure the project with several projections, on the fly and without it, and I always get the same message.
I do not know if it's a failure or I'm doing something wrong.
Thank you

ZoomRC version 0.4
QGIS 2.18.24
Windows 10

**Comment by fpsampayo** [comment]
Hi Emilio,

I just upload a new 0.4.1 versión to qgis plugin site[1]. We need to wait until the administrator approves the changes to alow the plugin to download from the qgis plugins tool. When this happen, please, download and test to confirm that all works as expected.

The problem syms to be with a catastro ssl certificate. I changed the url from https to http to avoid that problem.

1- https://plugins.qgis.org/plugins/zoomrc/

**Comment by EmilioAAbad** [comment]
Thanks Francisco, I think it's a great tool. 
I wait for the changes.

**Comment by fpsampayo** [comment]
The plugin is approbed! Try it!

**Comment by EmilioAAbad** [comment]
THANKS AGAIN, GREAT!  PLUGGIN WORKS!

Regards Francisco

**Comment by fpsampayo** [comment]
Thanks Emilio!
