### ISSUE TITLE
[FEATURE] Descarga masiva

### ISSUE THREAD

**Issue by pablohevia** [fpsampayo/zoomrc#6]
Hola, Francisco:

Tengo una lista de RCs enorme (cerca de 1000) y me gustaría saber si hay manera de automatizar el proceso de descarga de contornos.

Enhorabuena por el plugin, es estupendo.

**Comment by fpsampayo** [comment]
No me enteré de esto y hace ya 5 años :facepalm: 

Me imagino que ya arreglaste, pero no es el objetivo de este plugin, además, catastro es muy restrictivo con el uso de sus servicios, si lo habilitara seguramente conseguirías un baneo temporal (ya me ha pasado hace mucho). 
Igual lo mejor es que descargues los municipios objetivo si es uno o pocos y juntes todo ya pudiendo seleccionar esas parcelas.
